# Конфигурация Debafr
# Этот файл должен находится в корневой директории приложения

[app]
# Должно совпадать со значениями из compose.yaml:
# name: myapp
# services:
#  service_name:
#    labels:
#      - "app.project.name=myapp"
project_name = "myapp"
proxy_pass_prefix = "proxy_pass http://127.0.0.1:"
location_ports = [
    {location = "/api", blue_port = "3001", green_port = "3011"},
    {location = "/ws",  blue_port = "3003", green_port = "3013"},
    {location = "/",    blue_port = "3002", green_port = "3012"},
]

# Включение генерации targets для victoriametrics
# после переключения сервиса
#
# Использование:
# scrape_configs:
#   - job_name: "myapp_metrics"
#     metrics_path: /metrics
#     file_sd_configs:
#       - files:
#           - "/etc/victoriametrics/targets/myapp.json"
#         refresh_interval: 10s
[app.victoriametrics]
enabled = false
targets_output_file_path = ""
target_blue = ""
target_green = ""

[docker_login]
enabled = false
registry = ""
username = ""
password = ""

[files]
compose_blue = "compose.blue.yaml"
compose_green = "compose.green.yaml"
nginx_conf = "nginx.conf"

[binpaths]
docker = "/usr/bin/docker"
curl = "/usr/bin/curl"
nginx = "/usr/sbin/nginx"

[timeouts]
default = "30s"

[healthcheck]
max_retries = 10
retry_delay = "3s"
